from subprocess import run

# from pathlib import Path

# Path().absolute

disable = [
    "com.mi.android.globalminusscr@een",
    "com.miui.global.packageinstaller",
    "com.android.thememanager",
    "com.xiaomi.account",
    "com.miui.android.fashiongallery",
    "com.google.android.gms",
    "com.google.android.gsf",
]

uninstall = [
    "cn.wps.xiaomi.abroad.lite",
    "code.name.monkey.retromusic | Paranoid Android",
    "com.android.bips | Default Printing Service",
    "com.android.bookmarkprovider | Bookmark Provider",
    "com.android.browser | Web Browser",
    "com.android.calendar | Calendar app",
    "com.android.chrome | Chrome Browser (you may loose webview)",
    "com.android.contacts",
    # "com.android.deskclock | Stock Clock app",
    "com.android.dreams.basic | Screensaver app",
    "com.android.dreams.phototable | Screensaver app",
    "com.android.egg z| Android Easter Egg",
    "com.android.email",
    "com.android.emergency | SOS Calling",
    "com.android.frameworkhwext.honor",
    "com.android.hotwordenrollment.okgoogle | OK Google",
    "com.android.hotwordenrollment.xgoogle",
    "com.android.keyguard",
    "com.android.mediacenter",
    "com.android.mms | MMS app",
    "com.android.mms.service | MMS",
    "com.android.partnerbrowsercustomizations.tmobile",
    "com.android.printspooler | Printing service",
    "com.android.providers.calendar",
    "com.android.providers.downloads.ui",
    "com.android.soundrecorder",
    "com.android.statementservice | Checks APK files",
    "com.android.stk | SIM Tool-kit",
    "com.android.thememanager",
    "com.android.thememanager.module",
    "com.android.vending",
    "com.android.wallpaper.livepicker | Live wallpaper",
    "com.android.wallpaperbackup | Wallpaper backup feature",
    "com.android.wallpapercropper | Wallpaper cropping feature",
    "com.autonavi.minimap",
    "com.bsp.catchlog",
    "com.caf.fmradio",
    "com.dsi.ant.server",
    "com.duokan.phone.remotecontroller",
    "com.duokan.phone.remotecontroller.peel.plugin",
    "com.example.android.notepad",
    "com.facebook.appmanager",
    "com.facebook.appmanager | Facebook",
    "com.facebook.katana",
    "com.facebook.katana | Facebook",
    "com.facebook.services",
    "com.facebook.services | Facebook",
    "com.facebook.system",
    "com.facebook.system | Facebook",
    "com.google.android.apps.docs | Google Docs",
    "com.google.android.apps.googleassistant",
    "com.google.android.apps.maps | Google Maps",
    "com.google.android.apps.messaging",
    "com.google.android.apps.nbu.paisa.user | Google Pay",
    "com.google.android.apps.photos | Google Photos",
    "com.google.android.apps.restore",
    "com.google.android.apps.subscriptions.red",
    "com.google.android.apps.turbo",
    "com.google.android.apps.tachyon | Google Duo",
    "com.google.android.apps.wellbeing | Digital Wellbeing",
    "com.google.android.contacts",
    "com.google.android.dialer",
    "com.google.android.feedback | Feedback app",
    "com.google.android.gm | Gmail",
    "com.google.android.gms | Gmail service",
    "com.google.android.gms.location.history | Gmail location service",
    "com.google.android.googlequicksearchbox | Google Quick Search",
    "com.google.android.gsf",
    "com.google.android.inputmethod.latin | Gboard",
    "com.google.android.marvin.talkback | Talkback feature",
    "com.google.android.music | Google Play Music",
    "com.google.android.onetimeinitializer",
    "com.google.android.partnersetup",
    "com.google.android.printservice.recommendation | Mobile Printing",
    "com.google.android.projection.gearhead",
    "com.google.android.setupwizard",
    "com.google.android.syncadapters.calendar | Calendar Sync",
    "com.google.android.talk",
    "com.google.android.tts | Text-to-speech",
    "com.google.android.videos | Google Play Movies & TV",
    "com.google.android.youtube | Youtube",
    "com.google.ar.lens | AR Lens",
    "com.hampusolsson.abstruct | Paranoid Android",
    "com.huaqin.diaglogger",
    "com.huawei.android.FloatTasks",
    "com.huawei.contactscamcard",
    "com.huawei.featurelayer.sharedfeature.baidu",
    "com.huawei.featurelayer.sharedfeature.map",
    "com.huawei.hicard",
    "com.huawei.hitouch",
    "com.huawei.hwstartupguide",
    "com.huawei.livewallpaper.mountaincloud",
    "com.huawei.phoneservice",
    "com.huawei.search",
    "com.huawei.trustagent",
    "com.huawei.wallet",
    "com.mfashiongallery.emag",
    "com.mi.android.globalFileexplorer| Mi File Manager",
    "com.mi.android.globallauncher | Mi Launcher",
    "com.mi.android.globallauncher | POCO Launcher",
    "com.mi.android.globalpersonalassistant",
    "com.mi.global.bbs",
    "com.mi.global.shop",
    "com.mi.globalTrendNews",
    "com.mi.globalbrowser | Mi Browser",
    "com.mi.health | Mi Health",
    "com.mi.webkit.core | Mi Webkit",
    "com.micredit.in | MI credit",
    "com.milink.service",
    "com.mint.keyboard",
    "com.mipay.wallet.id | Mi Wallet",
    "com.mipay.wallet.in | Mi Wallet (India)",
    "com.miui.accessibility",
    "com.miui.analytics | MIUI Analytics (spyware)",
    "com.miui.android.fashiongallery | Wallpaper Carousel",
    "com.miui.antispam",
    "com.miui.aod | MIUI Always-on Display",
    "com.miui.backup | Backup app",
    "com.miui.bugreport | Bug reporting app",
    "com.miui.calculator | Mi Calculator",
    "com.miui.cit",
    "com.miui.cleanmaster | System Cleaner",
    "com.miui.cloudbackup | Cloud Backup service",
    "com.miui.cloudservice | Cloud service",
    "com.miui.cloudservice.sysbase | Cloud service",
    "com.miui.compass | MIUI Compass",
    "com.miui.contentcatcher",
    "com.miui.documentsuioverlay",
    "com.miui.enbbs",
    "com.miui.extraphoto | Camera Bokeh effect",
    "com.miui.face | MIUI Biometric",
    "com.miui.fm | MIUI FM",
    "com.miui.fmservice| MIUI FM",
    "com.miui.freeform | MIUI Picture in Picture service",
    "com.miui.gallery | MIUI Gallery",
    "com.miui.greenguard",
    "com.miui.huanji",
    "com.miui.hybrid | Quick Apps (data mining app)",
    "com.miui.hybrid.accessory | Quick Apps (data mining app)",
    "com.miui.klo.bugreport",
    "com.miui.micloudsync | Cloud Sync",
    "com.miui.miservice",
    "com.miui.mishare.connectivity | Mi Share",
    "com.miui.misound | Music app & sound enhancer",
    "com.miui.miwallpaper | Wallpaper app",
    "com.miui.miwallpaper.earth",
    "com.miui.miwallpaper.mars",
    "com.miui.msa.global | MSA or MIUI Ad Services",
    "com.miui.newmidrive",
    "com.miui.nextpay",
    "com.miui.notes | Notes",
    "com.miui.phrase | Frequent phrases",
    "com.miui.player | Music Player",
    "com.miui.providers.weather",
    "com.miui.qr",
    "com.miui.screenrecorder | Screen Recorder",
    "com.miui.smsextra | Text Message features",
    "com.miui.system | MIUI System Launcher",
    "com.miui.systemui.carriers.overlay | Carrier name chaging service",
    "com.miui.touchassistant | Quick Ball feature",
    "com.miui.translation.kingsoft",
    "com.miui.translation.youdao",
    "com.miui.translationservice",
    "com.miui.userguide | User Guide app",
    "com.miui.videoplayer | MIUI Video player",
    "com.miui.virtualsim",
    "com.miui.vsimcore",
    "com.miui.weather2 | Weather app",
    "com.miui.wmsvc",
    "com.miui.yellowpage | Yellow Page app",
    "com.miui.zman",
    "com.netflix.mediaclient | Netflix",
    "com.netflix.partner.activation | Netflix",
    "com.opera.app.news | Opera",
    "com.opera.branding | Opera",
    "com.opera.branding.news | Opera News",
    "com.opera.mini.native | Opera Mini",
    "com.opera.preinstall | Opera",
    "com.samsung.aasaservice",
    "com.sohu.inputmethod.sogou.xiaomi",
    "com.swiftkey.languageprovider",
    "com.swiftkey.swiftkeyconfigurator",
    "com.syberia.SyberiaPapers",
    "com.syberia.SyberiaPapers | SyberiaOS",
    "com.syberia.ota | SyberiaOS",
    "com.tencent.soter.soterserver | Chinese Payment service",
    "com.xiaomi.account | Mi Account (sensitive)",
    "com.xiaomi.calendar | Mi Calendar",
    "com.xiaomi.cameratools | Camera Tools",
    "com.xiaomi.channel",
    "com.xiaomi.discover | Xiaomi System apps updater",
    "com.xiaomi.glgm | Games",
    "com.xiaomi.joyose | Junk and safe to remove",
    "com.xiaomi.location.fused",
    "com.xiaomi.mi_connect_service",
    "com.xiaomi.micloud.sdk | Cloud App",
    "com.xiaomi.midrop | Mi Drop",
    "com.xiaomi.mipicks | GetApps(Xiaomi app store)",
    "com.xiaomi.miplay_client",
    "com.xiaomi.mircs | MIUI to MIUI Message",
    "com.xiaomi.mirecycle | Mi Recycle (MIUI Security)",
    "com.xiaomi.mirecycle | Mi Security (sensitive)",
    "com.xiaomi.mirror",
    "com.xiaomi.misettings | Mi Settings",
    "com.xiaomi.oversea.ecom",
    "com.xiaomi.payment | Mi Pay",
    "com.xiaomi.scanner | Scanner app",
    "com.xiaomi.simactivate.service",
    "com.xiaomi.xmsf | Xiaomi Service Framework",
    "com.xiaomi.xmsfkeeper | Xiaomi Service Framework",
    "in.amazon.mShop.android.shopping | Amazon",
    "org.lineageos.recorder | LineageOS",
    "org.lineageos.snap | LineageOS",
    "org.simalliance.openmobileapi.service",
    "pl.zdunex25.updater | Xiaomi.eu",
    "ros.ota.updater | RevolutionOS",
    "com.android.cellbroadcastreceiver.overlay.common",
    # #
    "com.miui.mediaeditor",
    "com.google.mainline.telemetry",
    "com.google.android.overlay.gmsconfig.common",
    "com.google.android.overlay.gmsconfig.gsa",
]

# fp = open("uninstall.txt", "w")
# for i in sorted(set(uninstall)):
#     fp.write('"' + i + '",\n')
# fp.close()

for idx, item in enumerate(uninstall):
    item = item.split("|")[0].strip()
    uninstall[idx] = item
print(uninstall)

# DO NOT UNINSTALL THESE
# "com.miui.securitycenter",
# "com.miui.securityadd",
# "com.xiaomi.finddevice"
# "com.android.deskclock",
# "com.google.android.webview",

# for app in disable:
#     run(["adb", "shell", "pm", "disable-user", f"{app}"])
for app in uninstall:
    ps = run(
        ["adb", "shell", "pm", "uninstall", "--user", "0", f"{app}"],
        capture_output=True,
        encoding="utf-8",
    )
    print(app, ps.stdout, end="")
    if "-1000" in ps.stdout:
        print(f"Couldn't uninstall {app}\n")
    # run(["adb", "shell", "cmd", "package ", "install-existing", app])
